ktor:
    application:
        modules:
            - ru.stvvllrt.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: passwordjwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
