ktor:
    application:
        modules:
            - ru.stvvllrt.library.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: postgres
  password: "1708"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor stvvllrt app"
